language: cpp

sudo: required

dist: trusty

compiler:
  - gcc

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get remove -qq cmake cmake-data
  - sudo apt-get autoremove -qq
  - sudo apt-get update -y -qq
  - sudo apt-get install -y -qq g++-6 libboost-all-dev cmake-data cmake python3
  - sudo update-alternatives --install /usr/bin/g++  g++  /usr/bin/g++-6  90
  - sudo update-alternatives --install /usr/bin/gcc  gcc  /usr/bin/gcc-6  90
  - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-6 90
  - sudo apt-get install -y -qq zlib1g-dev

before_script:
  - mkdir build
  - cd build
  - cmake ..

script:
  - make -j 1
  - make test

branches:
  only:
    - master

notifications:
  email:
    recipients:
      - i@bowhan.com
    on_success: change
    on_failure: always